from __future__ import annotations

import argparse
import secrets
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
DEFAULT_REPO_BASE = "https://raw.githubusercontent.com/Ludirus/Hydroxide-Rogue-Additions/main/"

TARGETS = {
    "rogue_lineage.lua": {
        "source": ROOT / "ROGUE" / "rogue_ui.lua",
        "entrypoint": "dist/rogue_lineage.lua",
    },
    "rogue_battlegrounds.lua": {
        "source": ROOT / "ROGUE_BATTLEGROUNDS" / "rlb.lua",
        "entrypoint": "dist/rogue_battlegrounds.lua",
    },
}


def normalize_repo_base(repo_base: str) -> str:
    return repo_base if repo_base.endswith("/") else repo_base + "/"


def lua_string_literal(value: str) -> str:
    return '"' + (
        value
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    ) + '"'


def xor_byte(left: int, right: int) -> int:
    return left ^ right


def crypt_payload(data: bytes, seed: int, carry: int) -> bytes:
    state = seed % 65536
    chain = carry % 256
    output = bytearray()

    for index, byte in enumerate(data, 1):
        state = (state * 73 + 41 + (index % 251)) % 65536
        key = state // 256
        encrypted = xor_byte(xor_byte(byte, key), chain)
        output.append(encrypted)
        chain = (encrypted + key + index) % 256

    return bytes(output)


def lua_decimal_escape(data: bytes) -> str:
    return "".join(f"\\{byte:03d}" for byte in data)


def chunk_bytes(data: bytes, chunk_size: int) -> list[bytes]:
    return [data[index:index + chunk_size] for index in range(0, len(data), chunk_size)]


def build_encrypted_script(source_path: Path, repo_base: str, entrypoint: str, chunk_size: int) -> tuple[str, int, int, int]:
    source_prefix = (
        "if getgenv then "
        f"getgenv().HYDROXIDE_REPO={lua_string_literal(repo_base)} "
        f"getgenv().HYDROXIDE_ENTRYPOINT={lua_string_literal(entrypoint)} "
        "end\n"
    ).encode("utf-8")
    plaintext = source_prefix + source_path.read_bytes()
    seed = secrets.randbelow(65535) + 1
    carry = secrets.randbelow(256)
    encrypted = crypt_payload(plaintext, seed, carry)
    chunks = chunk_bytes(encrypted, chunk_size)
    lua_chunks = ",\n    ".join(f'"{lua_decimal_escape(chunk)}"' for chunk in chunks)

    script = f"""-- Encrypted HYDROXIDE artifact generated by scripts/compile_dist.py.
-- Repo base: {repo_base}
-- Entrypoint: {entrypoint}
local payload = {{
    {lua_chunks}
}}

local HYDROXIDE_DEBUG_USER = "Caikunya"
local function is_hydroxide_debug_enabled()
    local default_enabled = false
    local ok, players = pcall(game.GetService, game, "Players")
    local local_player = ok and players and players.LocalPlayer or nil
    if local_player and local_player.Name == HYDROXIDE_DEBUG_USER then
        default_enabled = true
    end

    if getgenv then
        local env = getgenv()
        if env.HYDROXIDE_DEBUG ~= nil then
            return env.HYDROXIDE_DEBUG == true
        end
        if local_player then
            env.HYDROXIDE_DEBUG = default_enabled
        end
    end

    return default_enabled
end

local function debug_print(...)
    if is_hydroxide_debug_enabled() then
        print(...)
    end
end

local function set_hydroxide_load_stage(stage, detail)
    if not getgenv then
        return
    end

    local env = getgenv()
    env.HYDROXIDE_LOAD_STAGE = tostring(stage)
    env.HYDROXIDE_LOAD_DETAIL = detail == nil and nil or tostring(detail)
end

local seed = {seed}
local carry = {carry}
local byte = string.byte
local char = string.char
local floor = math.floor

local function bxor(left, right)
    local result = 0
    local bit = 1

    while left > 0 or right > 0 do
        local left_bit = left % 2
        local right_bit = right % 2

        if left_bit ~= right_bit then
            result = result + bit
        end

        left = (left - left_bit) / 2
        right = (right - right_bit) / 2
        bit = bit * 2
    end

    return result
end

local function decrypt(chunks)
    local state = seed
    local chain = carry
    local index = 0
    local output = table.create and table.create(#chunks) or {{}}

    for chunk_index = 1, #chunks do
        local chunk = chunks[chunk_index]
        local decoded = table.create and table.create(#chunk) or {{}}

        for position = 1, #chunk do
            index = index + 1
            state = (state * 73 + 41 + (index % 251)) % 65536

            local key = floor(state / 256)
            local encrypted = byte(chunk, position)
            local plain = bxor(bxor(encrypted, key), chain)

            decoded[position] = char(plain)
            chain = (encrypted + key + index) % 256
        end

        output[chunk_index] = table.concat(decoded)
    end

    return table.concat(output)
end

if getgenv then
    getgenv().HYDROXIDE_LAST_ERROR = nil
end
set_hydroxide_load_stage("dist_decrypting", "{entrypoint}")
debug_print("[HYDROXIDE] Encrypted artifact decrypting")
local code = decrypt(payload)
set_hydroxide_load_stage("dist_decrypted", #code)
debug_print("[HYDROXIDE] Encrypted artifact decrypted", #code)
local loaded, compile_error = loadstring(code)
if not loaded then
    if getgenv then
        getgenv().HYDROXIDE_LAST_ERROR = tostring(compile_error)
    end
    set_hydroxide_load_stage("dist_compile_error", compile_error)
    error("[HYDROXIDE] encrypted artifact compile failed: " .. tostring(compile_error))
end

local function trace_error(err)
    if debug and debug.traceback then
        return debug.traceback(err, 2)
    end
    return tostring(err)
end

set_hydroxide_load_stage("dist_source_running", "{entrypoint}")
local run_ok, result = xpcall(loaded, trace_error)
if not run_ok then
    if getgenv then
        getgenv().HYDROXIDE_LAST_ERROR = tostring(result)
    end
    set_hydroxide_load_stage("dist_runtime_error", result)
    error(result)
end

if not (getgenv and getgenv().HYDROXIDE_LAST_ERROR) then
    set_hydroxide_load_stage("dist_done", "{entrypoint}")
end
return result
"""
    return script, seed, carry, len(plaintext)


def compile_target(source_path: Path, output_path: Path, repo_base: str, entrypoint: str, chunk_size: int) -> None:
    script, seed, carry, plaintext_size = build_encrypted_script(source_path, repo_base, entrypoint, chunk_size)
    output_path.write_text(script, encoding="utf-8", newline="\n")
    print(f"Wrote {output_path.name}: plaintext={plaintext_size} entrypoint={entrypoint} seed={seed} carry={carry}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile HYDROXIDE scripts into encrypted Lua artifacts.")
    parser.add_argument(
        "--repo-base",
        default=DEFAULT_REPO_BASE,
        help="Raw GitHub base URL persisted for dependency loading and queued teleports.",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=4096,
        help="Encrypted payload bytes per Lua string chunk.",
    )
    parser.add_argument(
        "--rogue-entrypoint",
        default=TARGETS["rogue_lineage.lua"]["entrypoint"],
        help="Repo-relative or absolute URL that queued Rogue teleports should reload.",
    )
    parser.add_argument(
        "--battlegrounds-entrypoint",
        default=TARGETS["rogue_battlegrounds.lua"]["entrypoint"],
        help="Repo-relative or absolute URL that queued Battlegrounds teleports should reload.",
    )
    args = parser.parse_args()
    repo_base = normalize_repo_base(args.repo_base)

    if args.chunk_size < 512:
        raise ValueError("--chunk-size must be at least 512")

    DIST.mkdir(exist_ok=True)

    entrypoints = {
        "rogue_lineage.lua": args.rogue_entrypoint,
        "rogue_battlegrounds.lua": args.battlegrounds_entrypoint,
    }

    for output_name, target in TARGETS.items():
        source_path = target["source"]
        if not source_path.is_file():
            raise FileNotFoundError(source_path)
        compile_target(source_path, DIST / output_name, repo_base, entrypoints[output_name], args.chunk_size)

    print(f"Wrote {len(TARGETS)} encrypted script(s) to {DIST}")


if __name__ == "__main__":
    main()
